<div id="tribe-events-event-22787-1" class="tribe-events-category-adults post-22787 tribe_events type-tribe_events status-publish hentry tag-adult tag-adult-activity tag-me tag-online tag-online-event tag-online-local-me tag-portland tag-support-group tag-support-group-adults tribe_events_cat-adults cat_adults tribe-events--is-past-event tribe-events-venue-2817 tribe-events-organizer-17056 tribe-events-last" data-tribejson="{&quot;i18n&quot;:{&quot;find_out_more&quot;:&quot;Find out more \u00bb&quot;,&quot;for_date&quot;:&quot;Events for&quot;},&quot;eventId&quot;:&quot;22787-2022-10-01&quot;,&quot;title&quot;:&quot;Online LOCAL Portland, ME \u201cOpen\u201d Support Group for Adults, 10\/1\/22, 1:00 PM \u2013 3:00 PM ET&quot;,&quot;permalink&quot;:&quot;https:\/\/www.aane.org\/event\/online-local-portland-me-open-support-group-for-adults-10-1-22-100-pm-300-pm-et\/&quot;,&quot;imageSrc&quot;:&quot;&quot;,&quot;dateDisplay&quot;:&quot;October 1 @ 1:00 pm - 3:00 pm&quot;,&quot;imageTooltipSrc&quot;:&quot;&quot;,&quot;excerpt&quot;:&quot;<p>DESCRIPTION:\u00a0 This open group meets on the first Saturday of each month and is for post-high school adults who are on the autism spectrum or who suspect that they are and live within commuting distance of Portland, ME. WHEN:\u00a0 Saturday, October 1, 2022 TIME:\u00a0\u00a01:00 PM \u2013 3:00 PM ET WHERE:\u00a0 Online via Zoom FACILITATORS:\u00a0\u00a0Robert Lagos\u00a0(207)...<\/p>&quot;,&quot;categoryClasses&quot;:&quot;tribe-events-category-adults post-22787 tribe_events type-tribe_events status-publish hentry tag-adult tag-adult-activity tag-me tag-online tag-online-event tag-online-local-me tag-portland tag-support-group tag-support-group-adults tribe_events_cat-adults cat_adults tribe-events--is-past-event tribe-events-venue-2817 tribe-events-organizer-17056 tribe-events-last&quot;,&quot;startTime&quot;:&quot;October 1 @ 1:00 pm&quot;,&quot;endTime&quot;:&quot;October 1 @ 3:00 pm&quot;}">
	<h3 class="tribe-events-month-event-title"><a href="https://www.aane.org/event/online-local-portland-me-open-support-group-for-adults-10-1-22-100-pm-300-pm-et/" class="url">Online LOCAL Portland, ME “Open” Support Group for Adults, 10/1/22, 1:00 PM – 3:00 PM ET</a></h3>
<div id="tribe-events-tooltip-22787-2022-10-01" class="tribe-events-tooltip" style="bottom: -390.6px; display: none;">
		<h3 class="entry-title summary">Online LOCAL Portland, ME “Open” Support Group for Adults, 10/1/22, 1:00 PM – 3:00 PM ET</h3>

		<div class="tribe-events-event-body">
			<div class="tribe-event-duration">
				<abbr class="tribe-events-abbr tribe-event-date-start">October 1 @ 1:00 pm - 3:00 pm </abbr>
			</div>
			
			
			<div class="tribe-event-description"><p>DESCRIPTION:&nbsp; This open group meets on the first Saturday of each month and is for post-high school adults who are on the autism spectrum or who suspect that they are and live within commuting distance of Portland, ME. WHEN:&nbsp; Saturday, October 1, 2022 TIME:&nbsp;&nbsp;1:00 PM – 3:00 PM ET WHERE:&nbsp; Online via Zoom FACILITATORS:&nbsp;&nbsp;Robert Lagos&nbsp;(207)...</p></div>
			
			<span class="tribe-events-arrow"></span>
		</div>
	</div></div>